#=============================================
#   Cấu hình server
#=============================================
server:
  port: 8080
  tomcat:
    threads:
      max: 50
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/plain
      - text/html
    min-response-size: 2KB
  servlet:
    context-path: /api
#=============================================
#   Cấu hình Spring
#=============================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gredirect2
    username: root
    password: AlonaGM26
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
#    defer-datasource-initialization: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
#=============================================
#   Cấu hình Security
#=============================================
#  security:
#    user:
#      password: 12345
#      name: user
#=============================================
#   Cấu hình Logging
#=============================================
logging:
  file:
    name: logs/application.log
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}] %thread [%level] %logger{25} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
#  level:
#    org.springframework.security: debug
#=============================================
#   Cấu hình Custom
#=============================================
jwt:
  secret: vhbchieu-0325978045-vh.bchieu@gmail.com-buigm2002
  expiration: 86400000
cors:
  origins:
    - http://localhost:5173
    - http://localhost:3000